$lock_cmd = pidof hyprlock || hyprlock
$wake_cmd = hyprctl dispatch dpms on ; (pidof qs quickshell > /dev/null 2>&1 || qs -c floatg &) ; qs ipc call hyprsunset.refresh

general {
    lock_cmd = $lock_cmd
    unlock_cmd = qs ipc call hyprsunset.refresh
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = $wake_cmd
}

listener {
    timeout = 300 # 5mins
    on-timeout = loginctl lock-session
    on-resume = hyprctl dispatch dpms on ; qs ipc call hyprsunset.refresh
}

listener {
    timeout = 600 # 10mins
    on-timeout = hyprctl dispatch dpms off
    on-resume = $wake_cmd
}
